development:
  adapter: postgresql
  host: localhost
  username: postgres
  password: 123
  database: sample_app_dev

test:
  adapter: postgresql
  host: localhost
  username: postgres
  password: 123
  database: sample_app_test

production:
  adapter: postgresql
  host: localhost
  username: postgres
  password: 123
  database: sample_app_prod